# src/agent/candidate.py
"""
CLEAR Candidate Extraction and Normalization Layer

Responsible for parsing, deserializing, and normalizing LLM outputs.
This layer acts as a highly fault-tolerant "Polyfill", bridging the gap
between erratic SLM outputs and the strict JSON schema required by the Sandbox.
"""

from __future__ import annotations

import codecs
import json
from typing import Any

from langchain_core.messages import AIMessage, ToolMessage

from src.utils.parsers import extract_code_block, extract_json


def parse_tool_payload(message: ToolMessage) -> dict[str, Any] | None:
    """
    Safely deserializes the JSON telemetry emitted by the Docker Sandbox.
    """
    try:
        payload = json.loads(str(message.content))
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(payload, dict):
        return None

    return payload


def _unwrap_value(value: Any) -> Any:
    """
    Unwraps hallucinated, over-nested dictionary structures frequently
    generated by under-parameterized models (e.g., {"type": "string", "value": "code"}).
    """
    if not isinstance(value, dict):
        return value

    if isinstance(value.get("value"), str):
        return value["value"]

    for key in ("code", "source", "text", "content"):
        nested_value = value.get(key)
        if isinstance(nested_value, str):
            return nested_value

    return value


def _decode_escapes(value: Any) -> Any:
    """
    Decodes literal string escapes (\\n, \\t) injected by models that improperly
    serialize JSON payloads into raw text streams.
    """
    if not isinstance(value, str):
        return value

    if not any(token in value for token in ("\\n", "\\t", '\\"')):
        return value

    try:
        return codecs.decode(value, "unicode_escape")
    except Exception:
        return value


def normalise_args(arguments: Any) -> dict[str, str]:
    """
    Standardizes tool arguments, ensuring the runtime schema matches the
    strict Pydantic models expected by `run_repair_attempt`.
    """
    if not isinstance(arguments, dict):
        return {}

    cleaned: dict[str, str] = {}

    for key in ("code", "test_suite"):
        value = arguments.get(key)
        value = _unwrap_value(value)
        value = _decode_escapes(value)

        if isinstance(value, str):
            cleaned[key] = value

    return cleaned


def looks_like_plain_python(text: str) -> bool:
    """
    A heuristic analyzer to detect when a model completely fails to utilize
    Markdown fencing, emitting raw Python AST directly into the stream.
    """
    stripped = text.strip()

    if not stripped:
        return False

    obvious_prose_prefixes = (
        "here is",
        "the fix",
        "i will",
        "to fix",
        "this code",
        "explanation",
    )

    if stripped.lower().startswith(obvious_prose_prefixes):
        return False

    python_markers = (
        "def ",
        "async def ",
        "class ",
        "import ",
        "from ",
        "@",
        "#",
        "if ",
        "for ",
        "while ",
        "try:",
    )

    first_line = stripped.splitlines()[0].strip()

    if first_line.startswith(python_markers):
        return True

    return "=" in first_line


def extract_candidate_code(response_text: str) -> str:
    """
    Prioritizes strict Markdown extraction, falling back to heuristic
    source code detection if structural boundaries fail.
    """
    fenced_code = extract_code_block(response_text)
    if fenced_code:
        return fenced_code

    if looks_like_plain_python(response_text):
        return response_text.strip()

    return ""


def convert_text_response_to_tool_call(
    response_text: str,
    canonical_test_suite: str,
) -> AIMessage | None:
    """
    Translates raw text responses into native LangChain tool objects.
    This guarantees that the Sandbox receives a standardized interface,
    regardless of how badly the SLM degraded the output format.
    """
    payload = extract_json(response_text)

    # Path 1: The model attempted JSON but failed to wrap it in a tool call
    if isinstance(payload, dict):
        raw_arguments = payload.get("arguments", payload.get("args", payload))
        arguments = normalise_args(raw_arguments)
        candidate_code = arguments.get("code", "")

        if candidate_code.strip():
            return AIMessage(
                content="",
                tool_calls=[
                    {
                        "name": "run_repair_attempt",
                        "args": {
                            "code": candidate_code,
                            "test_suite": canonical_test_suite,
                        },
                        "id": "clear-json-tool-call",
                    }
                ],
            )

    # Path 2: The model output raw/Markdown code
    candidate_code = extract_candidate_code(response_text)

    if not candidate_code:
        return None

    return AIMessage(
        content="",
        tool_calls=[
            {
                "name": "run_repair_attempt",
                "args": {
                    "code": candidate_code,
                    "test_suite": canonical_test_suite,
                },
                "id": "clear-text-tool-call",
            }
        ],
    )
