"""
CLEAR Repair Artefact Management

Handles artefacts generated by:

- standalone src.main repair executions;
- automated multi-model benchmark experiments.

Benchmark child processes do not create separate experiment directories.
The parent benchmark runner remains responsible for batch-level reporting.
"""

from __future__ import annotations

import json
import re
import sys
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any, Iterator, TextIO


ANSI_ESCAPE_PATTERN = re.compile(
    r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])"
)


def make_safe_component(value: str) -> str:
    """Convert arbitrary text into a filename-safe component."""

    value = value.replace(":", "-")
    value = re.sub(r"[^A-Za-z0-9._+-]+", "-", value)

    return value.strip("-") or "unknown"


def write_text_atomic(path: Path, content: str) -> None:
    """
    Write a text file using a temporary file followed by replacement.

    This reduces the risk of partially written experiment artefacts.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_path = path.with_suffix(
        path.suffix + ".tmp"
    )

    temporary_path.write_text(
        content,
        encoding="utf-8",
    )

    temporary_path.replace(path)


def create_standalone_run_directory(
    *,
    model: str,
    benchmark: str,
    base_directory: str | Path | None = None,
) -> Path:
    """Create a timestamped directory for one standalone repair."""

    base_path = (
        Path(base_directory)
        if base_directory is not None
        else Path("tests/logs/single_runs")
    )

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    directory_name = (
        f"run_{timestamp}_"
        f"{make_safe_component(model)}_"
        f"{make_safe_component(benchmark)}"
    )

    run_directory = (
        base_path.resolve()
        / directory_name
    )

    # Handle the unlikely case of two runs beginning in the same second.
    suffix = 1
    original_directory = run_directory

    while run_directory.exists():
        run_directory = Path(
            f"{original_directory}_{suffix}"
        )
        suffix += 1

    run_directory.mkdir(
        parents=True,
        exist_ok=False,
    )

    return run_directory


class TeeStream:
    """
    Mirror text to the terminal and a plain-text execution log.

    ANSI terminal colour codes are removed from the saved log.
    """

    def __init__(
        self,
        primary_stream: TextIO,
        log_stream: TextIO,
    ) -> None:
        self.primary_stream = primary_stream
        self.log_stream = log_stream

    @property
    def encoding(self) -> str:
        """Return the underlying terminal encoding."""

        return (
            getattr(
                self.primary_stream,
                "encoding",
                None,
            )
            or "utf-8"
        )

    def write(self, text: str) -> int:
        """Write text to both destinations."""

        written = self.primary_stream.write(text)

        plain_text = ANSI_ESCAPE_PATTERN.sub(
            "",
            text,
        )

        self.log_stream.write(plain_text)

        return written

    def flush(self) -> None:
        """Flush both destinations."""

        self.primary_stream.flush()
        self.log_stream.flush()

    def isatty(self) -> bool:
        """Preserve terminal detection."""

        return self.primary_stream.isatty()

    def fileno(self) -> int:
        """Expose the underlying terminal descriptor."""

        return self.primary_stream.fileno()


@contextmanager
def mirror_console_output(
    log_path: str | Path,
) -> Iterator[None]:
    """Mirror stdout and stderr into one execution log."""

    resolved_path = Path(log_path).resolve()

    resolved_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    original_stdout = sys.stdout
    original_stderr = sys.stderr

    with resolved_path.open(
        "a",
        encoding="utf-8",
        buffering=1,
    ) as log_stream:
        sys.stdout = TeeStream(
            original_stdout,
            log_stream,
        )

        sys.stderr = TeeStream(
            original_stderr,
            log_stream,
        )

        try:
            yield
        finally:
            sys.stdout.flush()
            sys.stderr.flush()

            sys.stdout = original_stdout
            sys.stderr = original_stderr


def save_standalone_artifacts(
    *,
    run_directory: str | Path,
    original_code: str,
    test_suite: str,
    result: dict[str, Any],
    repaired_code: str | None = None,
    patch: str | None = None,
) -> None:
    """Save the files associated with one standalone repair."""

    run_path = Path(run_directory).resolve()

    write_text_atomic(
        run_path / "original.py",
        original_code,
    )

    write_text_atomic(
        run_path / "test_suite.py",
        test_suite,
    )

    artifact_index: dict[str, str | None] = {
        "execution_log": "execution.log",
        "original": "original.py",
        "test_suite": "test_suite.py",
        "repaired": None,
        "patch": None,
    }

    if repaired_code is not None:
        write_text_atomic(
            run_path / "repaired.py",
            repaired_code,
        )

        artifact_index["repaired"] = "repaired.py"

    if patch and patch.strip():
        write_text_atomic(
            run_path / "repair.patch",
            patch,
        )

        artifact_index["patch"] = "repair.patch"

    exported_result = {
        **result,
        "artifacts": artifact_index,
    }

    write_text_atomic(
        run_path / "result.json",
        json.dumps(
            exported_result,
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
    )


def materialise_benchmark_repairs(
    *,
    records: list[dict[str, Any]],
    run_directory: str | Path,
) -> list[dict[str, Any]]:
    """
    Save successful repaired files and patches from benchmark records.

    Private keys beginning with an underscore are removed from the public
    CSV and JSON records.
    """

    run_path = Path(run_directory).resolve()

    patches_directory = run_path / "patches"
    repairs_directory = run_path / "repairs"

    public_records: list[dict[str, Any]] = []

    for record in records:
        public_record = {
            key: value
            for key, value in record.items()
            if not key.startswith("_")
        }

        # Ensure consistent CSV columns for successful and failed records.
        public_record["patch_file"] = None
        public_record["repaired_file"] = None

        repair_patch = record.get("_repair_patch")
        repaired_code = record.get("_repaired_code")

        if record.get("passed") is True:
            filename_stem = "__".join(
                [
                    make_safe_component(
                        str(record.get("model", "unknown-model"))
                    ),
                    make_safe_component(
                        str(record.get("difficulty", "unknown-difficulty"))
                    ),
                    make_safe_component(
                        str(record.get("category", "unknown-category"))
                    ),
                    make_safe_component(
                        str(record.get("benchmark", "unknown-benchmark"))
                    ),
                ]
            )

            if isinstance(repair_patch, str) and repair_patch.strip():
                patch_path = (
                    patches_directory
                    / f"{filename_stem}.patch"
                )

                write_text_atomic(
                    patch_path,
                    repair_patch,
                )

                public_record["patch_file"] = (
                    patch_path.relative_to(run_path).as_posix()
                )

            if isinstance(repaired_code, str) and repaired_code.strip():
                repaired_path = (
                    repairs_directory
                    / f"{filename_stem}.py"
                )

                write_text_atomic(
                    repaired_path,
                    repaired_code,
                )

                public_record["repaired_file"] = (
                    repaired_path.relative_to(run_path).as_posix()
                )

        public_records.append(public_record)

    return public_records